INSERT INTO `pertanyaan`(`bidang`, `pertanyaan`, `type`) VALUES 
("Bidang Kurikulum", "Bagaimana tingkat kepuasan siswa/i terkait dengan materi yang disampaikan oleh setiap guru?", 1),
("Bidang Kurikulum", "Bagaimana tingkat kepuasan siswa/i dengan kualitas guru dalam mengajar teori?", 1),
("Bidang Kurikulum", "Bagaimana tingkat kepuasan siswa/i terkait dengan kedisiplinan guru dalam mengajar?", 1),
("Bidang Kurikulum", "Bagaimana tingkat kepuasan siswa/i terkait dengan kreativitas guru dalam menggunakan metode, media/alat dan sumber mengajar", 1),
("Bidang Kurikulum", "Bagaimana tingkat kepuasan siswa/i terkait dengan objektivitas guru dalam memberi penilaian dalam hal ketuntasan dan sikap?", 1),
("Bidang Kesiswaan", "Bagaimana tingkat kepuasan siswa/i terhadap kinerja kesiswaan dalam penegasan kedisiplinan dan tata tertib sekolah?", 1),
("Bidang Kesiswaan", "Bagaimana tingkat kepuasan siswa/i terhadap kontribusi bidang kesiswaan terhadap perkembangan siswa/i di sekolah terkait prestasi?", 1),
("Bidang Kesiswaan", "Bagaimana tingkat kepuasan siswa/i kontribusi bidang kesiswaan dalam penindaklanjutan/pemberian konsekuensi terhadap siswa/i yang terlambat berangkat sekolah?", 1),
("Bidang Kesiswaan", "Bagaimana tingkat kepuasan siswa/i terhadap pelaksanaan kedisiplinan di SMA Negeri 1 Demak sudah berjalan baik?", 1),
("Bidang Humas", "Bagaimana tingkat kepuasan siswa/i terhadap setiap informasi yang disampaikan oleh sekolah?", 1),
("Bidang Humas", "Bagaimana tingkat kepuasan siswa/i terhadap saluran komunikasi yang digunakan (papan informasi, media sosial, dsb) sudah cukup efektif sebagai sarana penyampaian informasi?", 1),
("Bidang Humas", "Bagaimana tingkat kepuasan siswa/i terhadap keresponsifan humas sekolah dalam menjawab pertanyaan atau keluhan dari siswa/i?", 1),
("Bidang Humas", "Bagaimana tingkat kepuasan siswa/i terhadap update informasi yang diberikan secara rutin seputar kegiatan dan kebijakan sekolah? ", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap kesesuaian fungsi ruangan yang ada di SMA N 1 Demak?", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap kelengkapan fasilitas yang tersedia di ruang?", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap kondisi saluran air saat hujan? ", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap sarana sekolah? (Meliputi ruang kelas, meja, kursi, papan tulis, dan LCD Proyektor) ", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap kebersihan dan kelengkapan sarana toilet SMA N 1 Demak? ", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap kondisi dan kelengkapan sarana olahraga atau sarana lainnya yang digunakan untuk menunjang kegiatan ekstrakurikuler? ", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap kondisi kebersihan dan kelengkapan sarana kantin sekolah? ", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap kelengkapan dan kebersihan tempat ibadah di sekolah? ", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terkait dengan pelayanan UKS?", 1),
("Bimbingan Konseling", "Bagaimana tingkat kepuasan siswa/i terhadap pelayanan BK ketika siswa mengalami masalah pribadi atau di lingkungan sekolah?", 1),
("Bimbingan Konseling", "Bagaimana tingkat kepuasan siswa/i terhadap pelayanan BK ketika siswa berkonsultasi jurusan saat akan masuk ke Perguruan Tinggi?", 1),
("Bimbingan Konseling", "Bagaimana tingkat kepuasan siswa/i terhadap informasi yang di berikan oleh BK seputar universitas dalam negeri, luar negeri, maupun sekolah kedinasan? ", 1),
("Bimbingan Konseling", "Bagaimana tingkat kepuasan siswa/i terhadap tanggapan guru BK yang selalu memberikan memotivasi/membangun untuk setiap masalah yang dihadapi siswa/i? ", 1),
("Bimbingan Konseling", "Bagaimana tingkat kepuasan siswa/i terhadap guru BK yang selalu menanggapi dengan baik ketika siswa mengungkapkan perasaan yang di alami?", 1),
("Bidang Pelayanan", "Bagaimana tingkat kepuasan siswa/i terhadap pelayanan petugas perpustakaan? ", 1),
("Bidang Pelayanan", "Bagaimana tingkat kepuasan siswa/i terhadap layanan umum yang diberikan oleh TU? ", 1),
("Bidang Pelayanan", "Bagaimana tingkat kepuasan siswa/i terhadap kelengkapan buku pegangan/referensi di perpustakaan?", 1);