INSERT INTO `pertanyaan`(`bidang`, `pertanyaan`, `type`) VALUES 
("Bidang Kurikulum", "Apakah siswa/i setuju atau tidak apabila guru membuat LKPD sesuai dengan tujuan pembelajaran? ", 2),
("Bidang Kurikulum", "Apakah siswa/i setuju atau tidak karena merasa nyaman dengan proses belajar yang digunakan selama kurikulum ini berlangsung?", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju atau tidak dengan tingkat pelaksanaan kedisiplinan di SMA Negeri 1 Demak sudah berjalan dengan baik?", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju atau tidak dengan sanksi yang tegas untuk siswa/i yang berangkat tidak tepatnya pada hari waktu? ", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju atau tidak jika diadakan pengecekan kelengkapan atribut setiap pagi? ", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju atau tidak dengan pengelolaan jadwal ekstrakurikuler yang ditetapkan di sekolah? ", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju atau tidak dengan peraturan penggunaan sepatu full hitam pada hari Senin dan Selasa? ", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju atau tidak dengan peraturan penggunaan kaos kaki berlogo SMA N 1 Demak pada hari Senin dan Selasa? ", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju atau tidak dengan peraturan pemakaian nametag berlogo SMA N 1 Demak atau bordir nama setiap hari? ", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju atau tidak apabila kesiswaan mengundang orang tua/wali murid bagi siswa/i yang bermasalah? ", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju atau tidak dengan diadakannya Kegiatan SEMULTIN pada hari Senin dapat meningkatkan kedisiplinan siswa/i SMA Negeri 1 Demak?", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju atau tidak dengan adanya Kegiatan SELASA BERLIAN pada hari Selasa dapat meningkatkan rasa peduli dalam diri siswa/i SMA Negeri 1 Demak untuk menjaga lingkungan dan dapat membantu dalam menjaga kebersihan sekolah?", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju atau tidak dengan adanya Kegiatan SAPA MASGI pada hari Rabu dapat meningkatkan kesadaran Siswa/i SMA Negeri 1 Demak akan pentingnya memilih makanan yang sehat dan bergizi? ", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju atau tidak dengan pelaksanaan Kegiatan TALQI yang dilakukan setiap hari Kamis sudah efektif?", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju atau tidak dengan Kegiatan TERAS BERSEMI (meliputi senam dan literasi numerasi) yang dilaksanakan pada hari Jum'at sudah efektif?", 2),
("Bidang Humas", "Apakah siswa/i setuju atau tidak dengan diadakannya Sosialisasi Ujian Sekolah dengan Orang tua/ Wali murid kelas Xll?", 2),
("Bimbingan Konseling", "Apakah siswa/i setuju atau tidak jika guru BK melakukan Daftar Cek Masalah/ Angket setiap setahun sekali guna mendalami perkembangan siswa/i? ", 2),
("Bimbingan Konseling", "Apakah siswa/i setuju atau tidak ketika guru BK memberikan informasi seluas-luasnya mengenai cara belajar untuk berprestasi? ", 2),
("Bimbingan Konseling", "Apakah para siswa/i setuju atau tidak dengan diadakannya Sosialisasi kepada Orang tua/Wali murid terkait dengan Mekanisme Pemilihan PTN melalui jalur SNBP/SNBT?", 2),
("Bimbingan Konseling", "Apakah para siswa/i setuju atau tidak dengan diadakannya bali omah atau mendatangkan alumni SMAN 1 setiap tahunnya?", 2),
("Bidang Pelayanan", "Apakah siswa/i setuju ketika hendak izin meninggalkan pelajaran harus melapor terlebih dahulu kepada guru piket?", 2);