INSERT INTO `pertanyaan`(`bidang`, `pertanyaan`, `type`) VALUES 
('Bimbingan Konseling', 'Bagaimana tingkat kepuasan siswa/i terhadap pelayanan BK ketika siswa mengalami masalah pribadi atau di lingkungan sekolah?', 1),
('Bimbingan Konseling', 'Bagaimana tingkat kepuasan siswa/i terhadap pelayanan BK ketika siswa berkonsultasi jurusan saat akan masuk ke Perguruan Tinggi?', 1),
('Bimbingan Konseling', 'Bagaimana tingkat kepuasan siswa/i terhadap informasi yang di berikan oleh BK seputar universitas dalam negeri, luar negeri, maupun sekolah kedinasan?', 1),
('Bimbingan Konseling', 'Bagaimana tingkat kepuasan siswa/i terhadap tanggapan guru BK yang selalu memberikan memotivasi/membangun untuk setiap masalah yang dihadapi siswa/i?', 1),
('Bimbingan Konseling', 'Bagaimana tingkat kepuasan siswa/i terhadap guru BK yang selalu menanggapi dengan baik ketika siswa mengungkapkan perasaan yang di alami?', 1),
('Bimbingan Konseling', 'Apakah siswa/i setuju jika guru BK melakukan Daftar Cek Masalah/ Angket setiap setahun sekali guna mendalami perkembangan siswa/i?', 2),
('Bimbingan Konseling', 'Apakah siswa/i setuju ketika guru BK memberikan informasi seluas-luasnya mengenai cara belajar untuk berprestasi?', 2),
('Bimbingan Konseling', 'Apakah kalian setuju dengan diadakannyaSosialisasi kepada Orang tua/Wali murid terkait dengan Mekanisme Pemilihan PTN melalui jalur SNBP/SNBT?', 2),
("Bidang Kurikulum", "Bagaimana tingkat kepuasan siswa/i terkait dengan materi yang disampaikan oleh setiap guru?", 1),
("Bidang Kurikulum", "Bagaimana tingkat kepuasan siswa/i terkait dengan kualitas guru dalam mengajar teori?", 1),
("Bidang Kurikulum", "Bagaimana tingkat kepuasan siswa/i terkait dengan kedisiplinan guru dalam mengajar?", 1),
("Bidang Kurikulum", "Bagaimana tingkat kepuasan siswa/i terkait dengan kreativitas guru dalam menggunakan metode, media/alat dan sumber mengajar?", 1),
("Bidang Kurikulum", "Bagaimana tingkat kepuasan siswa/i terkait dengan objektivitas guru dalam memberi penilaian dalam hal ketuntasan dan sikap?", 1),
("Bidang Kurikulum", "Apakah siswa/i setuju apabila guru membuat LKPD sesuai dengan tujuan pembelajaran?", 2),
("Bidang Kurikulum", "Apakah siswa/i merasa nyaman dengan proses belajar yang digunakan selama kurikulum ini berlangsung?", 2),
("Bidang Kesiswaan", "Bagaimana komunikasi yang terjalin antara pihak sekolah dengan orang tua/wali siswa?", 1),
("Bidang Kesiswaan", "Bagaimana kontribusi bidang kesiswaan terhadap perkembangan siswa/i di sekolah terkait prestasi?", 1),
("Bidang Kesiswaan", "Bagaimana kinerja kesiswaan dalam penindaklanjutan/pemberian konsekuensi terhadap siswa/i yang terlambat berangkat sekolah?", 1),
("Bidang Kesiswaan", "Bagaimana kinerja kesiswaan dalam penegasan kedisiplinan dan tata tertib sekolah?", 1),
("Bidang Kesiswaan", "Bagaimana kinerja kesiswaan dalam hal pengecekan atribut kelengkapan seragam?", 1),
("Bidang Kesiswaan", "Bagaimana pengelolaan jadwal ekstrakurikuler yang ditetapkan di sekolah?", 1),
("Bidang Kesiswaan", "Apakah tingkat pelaksanaan kedisiplinan di SMA Negeri 1 Demak sudah berjalan dengan baik?", 2),
("Bidang Kesiswaan", "Apakah siswa/i sepakat dengan sanksi yang tegas untuk siswa/i yang berangkat tidak tepat waktu?", 2),
("Bidang Kesiswaan", "Apakah siswa/i sepakat jika diadakan pengecekan kelengkapan atribut setiap pagi?", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju dengan peraturan penggunaan sepatu full hitam pada hari Senin dan Selasa?", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju dengan peraturan penggunaan kaos kaki berlogo SMA N 1 Demak pada hari Senin dan Selasa?", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju dengan peraturan pemakaian nametag berlogo SMA N 1 Demak atau bordir nama setiap hari?", 2),
("Bidang Kesiswaan", "Apakah siswa/i setuju apabila kesiswaan mengundang orang tua/wali murid bagi siswa/i yang bermasalah?", 2),
("Bidang Kesiswaan", "Setujukah siswa/i dengan diadakannya Kegiatan SEMULTIN pada hari Senin dapat meningkatkan kedisiplinan siswa/i SMA Negeri 1 Demak?", 2),
("Bidang Kesiswaan", "Apakah dengan adanya Kegiatan SELASA BERLIAN pada hari Selasa dapat meningkatkan rasa peduli dalam diri siswa/i SMA Negeri 1 Demak untuk menjaga lingkungan dan dapat membantu dalam menjaga kebersihan sekolah?", 2),
("Bidang Kesiswaan", "Apakah dengan adanya Kegiatan SAPA MASGI pada hari Rabu dapat meningkatkan kesadaran Siswa/i SMA Negeri 1 Demak akan pentingnya memilih makanan yang sehat dan bergizi?", 2),
("Bidang Kesiswaan", "Menurut Siswa/i, apakah pelaksanaan Kegiatan TALQI yang dilakukan setiap hari Kamis sudah efektif?", 2),
("Bidang Kesiswaan", "Apakah Kegiatan TERAS BERSEMI (meliputi senam dan literasi numerasi) yang dilaksanakan pada hari Jum'at sudah efektif?", 2),
("Bidang Humas", "Bagaimana tingkat kepuasan siswa/i terhadap keresponsifan humas sekolah dalam menjawab pertanyaan atau keluhan dari siswa/i?", 1),
("Bidang Humas", "Bagaimana tingkat kepuasan siswa/i terhadap update informasi yang diberikan secara rutin seputar kegiatan dan kebijakan sekolah?", 1),
("Bidang Humas", "Bagaimana tingkat kepuasan siswa/i terhadap setiap informasi yang disampaikan oleh sekolah?", 1),
("Bidang Humas", "Bagaimana tingkat kepuasan atas saluran komunikasi yang digunakan (papan informasi, media sosial, dsb) sudah cukup efektif sebagai sarana penyampaian informasi?", 1),
("Bidang Humas", "Apakah siswa/i setuju dengan di adakannya Sosialisasi Ujian Sekolah dengan Orang tua/ Wali murid kelas XII?", 2),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap kesesuaian fungsi ruangan yang ada di SMA N 1 Demak?", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap kondisi saluran air saat hujan?", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap sarana sekolah? (Meliputi ruang kelas, meja, kursi, papan tulis, dan LCD Proyektor)", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap kebersihan dan kelengkapan sarana toilet SMA Negeri 1 Demak?", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap kondisi dan kelengkapan sarana olahraga atau sarana lainnya yang digunakan untuk menunjang kegiatan ekstrakurikuler?", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap kondisi kebersihan dan kelengkapan sarana kantin sekolah?", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap kelengkapan dan kebersihan tempat ibadah di sekolah?", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap dengan pelayanan UKS?", 1),
("Bidang Sarpras", "Bagaimana tingkat kepuasan siswa/i terhadap fasilitas yang tersedia di ruang kelas?", 1),
("Bidang Pelayanan", "Bagaimana tingkat kepuasan siswa/i terhadap pelayanan petugas perpustakaan?", 1),
("Bidang Pelayanan", "Bagaimana tingkat kepuasan siswa/i terhadap layanan umum yang diberikan oleh TU?", 1),
("Bidang Pelayanan", "Bagaimana tingkat kepuasan siswa/i terhadap kelengkapan buku pegangan/referensi di perpustakaan?", 1),
("Bidang Pelayanan", "Apakah siswa/i setuju ketika hendak izin meninggalkan pelajaran harus melapor terlebih dahulu kepada guru piket?", 2);